server.name: kibana
server.host: "0.0.0.0"
elasticsearch.hosts: [ "http://elasticsearch:9200" ]

# Enable security for login
xpack.security.enabled: true
xpack.encryptedSavedObjects.encryptionKey: "min-32-byte-long-strong-encryption-key-here-for-saved-objects"

# Monitoring
monitoring.ui.container.elasticsearch.enabled: true
